In [3]:
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors

In [4]:
data = pd.read_csv('book_recom.csv')
data.head()

userID        ISBN  bookRating             bookTitle  totalRatingCount  \
0  276725  034545104X           0  Flesh Tones: A Novel                60   
1    2313  034545104X           5  Flesh Tones: A Novel                60   
2    6543  034545104X           0  Flesh Tones: A Novel                60   
3    8680  034545104X           5  Flesh Tones: A Novel                60   
4   10314  034545104X           9  Flesh Tones: A Novel                60   

                            Location  
0                  tyler, texas, usa  
1              cincinnati, ohio, usa  
2           strafford, missouri, usa  
3  st. charles county, missouri, usa  
4             beaverton, oregon, usa

In [19]:
data_pivot = data.pivot_table(index = 'bookTitle', columns = 'userID', values = 'bookRating').fillna(0)
data_pivot.head()

userID                                              14      23      26      \
bookTitle                                                                    
1st to Die: A Novel                                    0.0     0.0     0.0   
A Child Called \It\": One Child's Courage to Su...     0.0     0.0     0.0   
A Cold Heart: An Alex Delaware Novel                   0.0     0.0     0.0   
A Kiss of Shadows (Meredith Gentry Novels (Pape...     0.0     0.0     0.0   
A Man in Full                                          0.0     0.0     0.0   

userID                                              51      67      99      \
bookTitle                                                                    
1st to Die: A Novel                                    0.0     0.0     0.0   
A Child Called \It\": One Child's Courage to Su...     0.0     0.0     0.0   
A Cold Heart: An Alex Delaware Novel                   0.0     0.0     0.0   
A Kiss of Shadows (Meredith Gentry Novels (Pape...     0.0     0.0     0.0   
A Man in Full                                          0.0     0.0     0.0   

userID                                              135     243     254     \
bookTitle                                                                    
1st to Die: A Novel                                    0.0     0.0     0.0   
A Child Called \It\": One Child's Courage to Su...     0.0     0.0     0.0   
A Cold Heart: An Alex Delaware Novel                   0.0     0.0     0.0   
A Kiss of Shadows (Meredith Gentry Novels (Pape...     0.0     0.0     0.0   
A Man in Full                                          0.0     0.0     0.0   

userID                                              256      ...    278483  \
bookTitle                                                    ...             
1st to Die: A Novel                                    0.0   ...       0.0   
A Child Called \It\": One Child's Courage to Su...     0.0   ...       0.0   
A Cold Heart: An Alex Delaware Novel                   0.0   ...       0.0   
A Kiss of Shadows (Meredith Gentry Novels (Pape...     0.0   ...       0.0   
A Man in Full                                          0.0   ...       0.0   

userID                                              278514  278535  278552  \
bookTitle                                                                    
1st to Die: A Novel                                    0.0    10.0     0.0   
A Child Called \It\": One Child's Courage to Su...     0.0     0.0     0.0   
A Cold Heart: An Alex Delaware Novel                   0.0     0.0     0.0   
A Kiss of Shadows (Meredith Gentry Novels (Pape...     0.0     0.0     0.0   
A Man in Full                                          0.0     0.0     0.0   

userID                                              278582  278633  278740  \
bookTitle                                                                    
1st to Die: A Novel                                    0.0     0.0     0.0   
A Child Called \It\": One Child's Courage to Su...     0.0     0.0     0.0   
A Cold Heart: An Alex Delaware Novel                   0.0     0.0     0.0   
A Kiss of Shadows (Meredith Gentry Novels (Pape...     0.0     0.0     0.0   
A Man in Full                                          0.0     0.0     0.0   

userID                                              278769  278773  278843  
bookTitle                                                                   
1st to Die: A Novel                                    0.0     0.0     0.0  
A Child Called \It\": One Child's Courage to Su...     0.0     0.0     0.0  
A Cold Heart: An Alex Delaware Novel                   0.0     0.0     0.0  
A Kiss of Shadows (Meredith Gentry Novels (Pape...     0.0     0.0     0.0  
A Man in Full                                          0.0     0.0     0.0  

[5 rows x 11337 columns]

In [20]:
book_matrix = csr_matrix(data_pivot)
book_matrix

<198x11337 sparse matrix of type '<class 'numpy.float64'>'
	with 11110 stored elements in Compressed Sparse Row format>

In [21]:
model = NearestNeighbors(metric = 'cosine', algorithm = 'brute')
model.fit(book_matrix)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
         metric_params=None, n_jobs=None, n_neighbors=5, p=2, radius=1.0)

In [42]:
query_index = np.random.choice(len(data_pivot))
print(query_index)

22


In [43]:
data_pivot.iloc[query_index,:].values.reshape(1,-1)

array([[0., 0., 0., ..., 0., 0., 0.]])

In [44]:
distance,indices = model.kneighbors(data_pivot.iloc[query_index,:].values.reshape(1,-1), 
                                    n_neighbors = 6)

In [45]:
distance

array([[6.66133815e-16, 9.38792934e-01, 9.54492317e-01, 9.56172065e-01,
        9.63980405e-01, 9.65277733e-01]])

In [46]:
indices

array([[ 22,  94,  70, 184, 173,  43]], dtype=int64)

In [47]:
indices.flatten()

array([ 22,  94,  70, 184, 173,  43], dtype=int64)

In [48]:
# Recommending top 5 books
for i in indices.flatten()[1:]:
    print(data_pivot.index[i])

Night Sins
I Is for Innocent
The Voice of the Night
The Ritual Bath (Peter Decker &amp; Rina Lazarus Novels (Paperback))
Deja Dead
