In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier

In [4]:
heart = pd.read_csv('heart.csv')
heart.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [5]:
x = heart.iloc[::,:13]
y = heart.iloc[::,13:]

In [7]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3, random_state = 0)

# DecisionTree

In [9]:
dt = DecisionTreeClassifier(criterion = 'entropy', min_samples_split = 5, splitter = 'random', min_samples_leaf = 5)
dt.fit(x_train,y_train)
dt_pred = dt.predict(x_test)
dt_cm = metrics.confusion_matrix(dt_pred,y_test)
dt_accu = metrics.accuracy_score(dt_pred,y_test)
print(dt_cm)
print(dt_accu)

[[33  8]
 [11 39]]
0.7912087912087912


# RandomForest

In [13]:
rf = RandomForestClassifier(n_estimators = 100, random_state = 0)
rf.fit(x_train,y_train)
rf_pred = rf.predict(x_test)
rf_cm = metrics.confusion_matrix(rf_pred,y_test)
rf_accu = metrics.accuracy_score(rf_pred,y_test)
print(rf_cm)
print(rf_accu)

[[33  4]
 [11 43]]
0.8351648351648352


# AdaBoost

In [15]:
ab = AdaBoostClassifier(n_estimators = 100, random_state = 0)
ab.fit(x_train,y_train)
ab_pred = ab.predict(x_test)
ab_cm = metrics.confusion_matrix(ab_pred,y_test)
ab_accu = metrics.accuracy_score(ab_pred,y_test)
print(ab_cm)
print(ab_accu)

[[33  8]
 [11 39]]
0.7912087912087912


# GradientBoosting

In [17]:
gb = GradientBoostingClassifier(n_estimators = 100, random_state = 0)
gb.fit(x_train,y_train)
gb_pred = gb.predict(x_test)
gb_cm = metrics.confusion_matrix(gb_pred,y_test)
gb_accu = metrics.accuracy_score(gb_pred,y_test)
print(gb_cm)
print(gb_accu)

[[34  6]
 [10 41]]
0.8241758241758241


# XGBoost

In [19]:
from xgboost import XGBClassifier

In [20]:
xg = XGBClassifier()
xg.fit(x_train,y_train)
xg_pred = xg.predict(x_test)
xg_cm = metrics.confusion_matrix(xg_pred,y_test)
xg_accu = metrics.accuracy_score(xg_pred,y_test)
print(xg_cm)
print(xg_accu)

[[31  5]
 [13 42]]
0.8021978021978022


In [12]:
import warnings
warnings.filterwarnings('ignore')